"""Suppression de test à Post

Revision ID: 17740c7f9f05
Revises: 577b7e8e07b6
Create Date: 2025-11-08 06:01:44.418764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17740c7f9f05'
down_revision: Union[str, Sequence[str], None] = '577b7e8e07b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'test')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('test', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
